default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: social_development

test:
  <<: *default
  database: social_test

production:
  <<: *default
  database: social_production
  username: social
  password: <%= ENV['social_DATABASE_PASSWORD'] %>
